package sdu.project.cinemaapp.utills.defaultObjects

import sdu.project.cinemaapp.domain.model.Movie


val defaultMovie = Movie(
        kinopoiskId = 0,
        kinopoiskHDId = null,
        imdbId = null,
        nameRu = null,
        nameEn = null,
        nameOriginal = null,
        posterUrl = null,
        posterUrlPreview = null,
        coverUrl = null,
        logoUrl = null,
        reviewsCount = null,
        ratingGoodReview = null,
        ratingGoodReviewVoteCount = null,
        ratingKinopoisk = null,
        ratingKinopoiskVoteCount = null,
        ratingImdb = null,
        ratingImdbVoteCount = null,
        ratingFilmCritics = null,
        ratingFilmCriticsVoteCount = null,
        ratingAwait = null,
        ratingAwaitCount = null,
        ratingRfCritics = null,
        ratingRfCriticsVoteCount = null,
        webUrl = null,
        year = null,
        filmLength = null,
        slogan = null,
        description = null,
        shortDescription = null,
        editorAnnotation = null,
        isTicketsAvailable = null,
        productionStatus = null,
        type = null,
        ratingMpaa = null,
        ratingAgeLimits = null,
        hasImax = null,
        has3D = null,
        lastSync = null,
        countries = emptyList(),
        genres = emptyList(),
        startYear = null,
        endYear = null,
        serial = null,
        shortFilm = null,
        completed = null,
        professionKey = null,
        isWatched = false,
        collectionName = null
    )
